name: Build LaTeX document
on:
  push:
    paths-ignore:
      - 'resume.png'
      - 'main.pdf'
      - '**.md'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          fetch-depth: 0
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
      
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8  # Adjust timezone as needed
          format: 'YYYY-MM-DD-HH-mm-ss'
      
      - name: Install ghostscript and imagemagick
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y ghostscript imagemagick
      
      - name: Change ImageMagick security policy
        run: |
          DQT='"' 
          SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
          RPL="rights=${DQT}read\|write${DQT} pattern=${DQT}PDF${DQT}"
          
          # Update ImageMagick policy to allow PDF processing
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml
          
          # Increase resource limits in policy.xml
          sudo sed -i "s/name=\"height\" value=\"[^\"]*\"/name=\"height\" value=\"128KP\"/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/name=\"width\" value=\"[^\"]*\"/name=\"width\" value=\"128KP\"/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/name=\"area\" value=\"[^\"]*\"/name=\"area\" value=\"128MP\"/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/name=\"disk\" value=\"[^\"]*\"/name=\"disk\" value=\"8GiB\"/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/name=\"map\" value=\"[^\"]*\"/name=\"map\" value=\"4GiB\"/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/name=\"memory\" value=\"[^\"]*\"/name=\"memory\" value=\"2GiB\"/" /etc/ImageMagick-6/policy.xml
      
      - name: Convert PDF to PNG
        run: convert -density 900 -background white -alpha off main.pdf -resize 25% -quality 90 -colorspace RGB resume.png
      
      - name: Commit PNG and PDF
        id: commit
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add resume.png main.pdf
          git commit -m "[bot] updated resume.png and main.pdf at ${{ steps.time.outputs.time }}" || echo "No changes to commit"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: ${{ github.ref_name }}
